### ISSUE TITLE
Everything works fine except the hot reload

### ISSUE THREAD

**Issue by adyz** [madole/webpack-dev-middleware-boilerplate#2]
Awesome project. It's exactly something that I was thinking it would be nice to have in my project. Express + HotReload.

I installed all the packages, and everything worked fined regarding the installation

It does compile any changes that I make on index.jade for example, except that there is no hot reload.

Have you tried starting this project lately? Do you have any idea why would that be?

Thank you

**Comment by madole** [comment]
I'd recommend using Webpack Dev Server (https://webpack.github.io/docs/webpack-dev-server.html) now over the Dev middleware approach. 

But in the meantime, you'll only get hot reloading of front end assets, CSS and JS. As your jade template is getting rendered serverside, nodemon is probably restarting your app and webpack will refresh your browser when it detects something has changed (or that might not even happen). 

Try changing some of the JS or CSS and see if the hot reloading works for you then let me know.

**Comment by adyz** [comment]
Thanks a lot for your answer, I understand a little bit more about webpack. 


I will look further into the webpack-dev-server, even if I am not sure that it will be possible to integrate that with my current express server.

Have a great day!
